---
title: "R Notebook"
output: html_notebook
---


Read data

```{r}
a = as.matrix(read.csv("ContactMatrixAll_5AgeGroups.csv",header = F))
b = read.csv("AustinMSA Population - 5 age groups.csv")
pp=tail( colSums(b),5)
Pop_Metro=pp
Pop_Metro2.in = b[,-(1:2)]
phi2.in=(a)
```


This part is only needed for debugging. Ignore
```{r eval=FALSE}
phi2 = phi2
Pop_Metro2 = Pop_Metro2
T_Y_TO_R_PARA = 22.6  # median of  [21.1, 22.6, 24.4]
T_EXPOSED_PARA = 7.0 # median of  [5.6, 7, 8.2]
ASYMP_RATE = 0.179
PROP_TRANS_IN_E = 0.126
T_ONSET_TO_H = 5.9
T_H_TO_R = 14.0
T_H_TO_D = 14.0 
symp_h_ratio_overall = c(0.00048721, 0.00048721, 0.03287572, 0.11337395, 0.17733063)
hosp_f_ratio = c(0.04 , 0.12365475, 0.03122403, 0.10744644, 0.23157691)
symp_h_ratio = rbind( 
		c(2.79135866e-04, 2.14621858e-04, 1.32154040e-02, 2.85633688e-02, 3.38733218e-02),
		c(2.79135866e-03, 2.14621858e-03, 1.32154040e-01, 2.85633688e-01, 3.38733218e-01) )
symp_h_ratio_corrrect = c(
		1.610326595443765, 1.924464960134284, 2.31133016137442, 3.724051596082457, 4.95257504190157
	) # hospitalization is 10 times higher for high risk individuals. I made an average of 1*[num low]+10*[num high] for each age class.


N.pat=3

Pop_Metro = colSums( Pop_Metro2 )

phiM = 1 / Pop_Metro * phi2 
phiLTC = 1 / 200 * phi2 *10
phi.L = array( 0, c(5,N.pat,5))
phi.L[,1,] = phiM

phi.L[,-1,] = phiLTC


	
	gamma_h = 1.0 / T_H_TO_R 
	gamma_y_c = 1.0 / T_Y_TO_R_PARA 
	gamma_y = gamma_y_c 
	gamma_a = gamma_y 

	sigma_c = 1.0 / T_EXPOSED_PARA 
	sigma = sigma_c ;

	eta = 1.0 / T_ONSET_TO_H 

	mu = 1.0 / T_H_TO_D 

	tau = 1.0 - ASYMP_RATE 

	omega_y = 1.0 ;
	omega_h = 0.0 ;

	#Only needed when there are no risk groups
	#for( i=0; i<g.ngroup; i++)
	#	symp_h_ratio[i] *= symp_h_ratio_corrrect[i] ;

	
	
	nu = hosp_f_ratio * gamma_h / (mu  + (gamma_h - mu  ) * hosp_f_ratio )  # hosp_f_ratio is an array of size age.
	pi = symp_h_ratio * gamma_y / (eta + (gamma_y - eta   ) * symp_h_ratio )  # symp_h_ratio is an array of size risk * age
	# omega_e - relative infectiousness in E, IY, IA // symp_h_ratio_overall length age. 
	#omega_e = ((symp_h_ratio_overall / eta) + ((1 - symp_h_ratio_overall ) / gamma_y)) * 
	#					omega_y * sigma * PROP_TRANS_IN_E / (1 - PROP_TRANS_IN_E)            
	omega_e = ((symp_h_ratio / eta) + ((1 - symp_h_ratio ) / gamma_y)) * 
						omega_y * sigma * PROP_TRANS_IN_E / (1 - PROP_TRANS_IN_E)            
	# length age
	omega_a = ((symp_h_ratio_overall / eta) + ((1 - symp_h_ratio_overall) / gamma_y_c)) * 
						omega_y * sigma_c * PROP_TRANS_IN_E / (1 - PROP_TRANS_IN_E) ;
	
	

S=1; E=2; IY=3; IA=4; IH=5; RAY=6; RH=7 ; D=8
ZERO = array(0, c(5,N.pat,2,8))
n=length(ZERO)
c1=ZERO
c1[c(E,IY,IA,IH),,,]=1

oo=array(1:length(ZERO),dim(ZERO))
# each entry in o1, o2 says where it comes from, from which entry in dX1, dX2 we should add.
o1=ZERO;o2=ZERO;o1[]=oo[,,,D];o2[]=oo[,,,D] # initially, everything comes from D, because D will not change, so dX1, dX2 for D is 0.
oo[,,,c(S)] ->o1[,,,c(E)]
oo[,,,c(E)] ->o1[,,,c(IA)]; oo[,,,c(E)] ->o2[,,,c(IY)]
oo[,,,c(IY)]->o1[,,,c(IH)]; oo[,,,c(IY)]->o2[,,,c(RAY)]
oo[,,,c(IH)]->o1[,,,c(D)];  oo[,,,c(IH)]->o2[,,,c(RH)]
oo[,,,c(IA)]->o1[,,,c(RAY)]


# o1[,,c(S,IY,RH)] are themselves, and dI1 needs to be 0 there.
# o2[,,c(S,IA,IH,D,RH)] are themselves, and dI2 needs to be 0 there.


#c1 - How much does each category contribute to infections

c1 = ZERO # 0
c1[,,,E]  = omega_e
c1[,,,IY] = omega_y
c1[,,,IH] = omega_h
c1[,,,IA] = omega_a

c2 = ZERO
c2[,,,S] = 1

c3 = ZERO
c3[,,,E]  = sigma
c3[,,,IA] = gamma_a
c3[,,,IY] = (1-pi)*gamma_y + pi*eta
c3[,,,IH] = (1-nu)*gamma_h + nu*mu

p2 = ZERO
p2[,,,E] = tau
p2[,,,IY] = (1-pi)*gamma_y / ( (1-pi)*gamma_y + pi*eta )
p2[,,,IH] = (1-nu)*gamma_h / ((1-nu)*gamma_h + nu*mu)


```


Function for building the stochastic and deterministic dynamics function.

```{r}

make.SEIR.f=function( 
phi2 = phi2.in,
Pop_Metro2 = Pop_Metro2.in,
T_Y_TO_R_PARA = 22.6,  # median of  [21.1, 22.6, 24.4]
T_EXPOSED_PARA = 7.0, # median of  [5.6, 7, 8.2]
ASYMP_RATE = 0.179,
PROP_TRANS_IN_E = 0.126,
T_ONSET_TO_H = 5.9,
T_H_TO_R = 14.0 ,
T_H_TO_D = 14.0 ,
symp_h_ratio_overall = c(0.00048721, 0.00048721, 0.03287572, 0.11337395, 0.17733063),
hosp_f_ratio = c(0.04 , 0.12365475, 0.03122403, 0.10744644, 0.23157691),
symp_h_ratio = rbind( 
		c(2.79135866e-04, 2.14621858e-04, 1.32154040e-02, 2.85633688e-02, 3.38733218e-02),
		c(2.79135866e-03, 2.14621858e-03, 1.32154040e-01, 2.85633688e-01, 3.38733218e-01) ),
symp_h_ratio_corrrect = c(
		1.610326595443765, 1.924464960134284, 2.31133016137442, 3.724051596082457, 4.95257504190157
	), # hospitalization is 10 times higher for high risk individuals. I made an average of 1*[num low]+10*[num high] for each age class.
N.pat=N.pat, pat.size=200
) {
Pop_Metro = colSums( Pop_Metro2 )

phiM = 1 / Pop_Metro * phi2 
phiLTC = 1 / pat.size * phi2 *10
phi.L = array( 0, c(5,N.pat,5))
phi.L[,1,] = phiM

phi.L[,-1,] = phiLTC



	
	gamma_h = 1.0 / T_H_TO_R 
	gamma_y_c = 1.0 / T_Y_TO_R_PARA 
	gamma_y = gamma_y_c 
	gamma_a = gamma_y 

	sigma_c = 1.0 / T_EXPOSED_PARA 
	sigma = sigma_c ;

	eta = 1.0 / T_ONSET_TO_H 

	mu = 1.0 / T_H_TO_D 

	tau = 1.0 - ASYMP_RATE 

	omega_y = 1.0 ;
	omega_h = 0.0 ;

	#Only needed when there are no risk groups
	#for( i=0; i<g.ngroup; i++)
	#	symp_h_ratio[i] *= symp_h_ratio_corrrect[i] ;

	
	
	nu = hosp_f_ratio * gamma_h / (mu  + (gamma_h - mu  ) * hosp_f_ratio )  # hosp_f_ratio is an array of size age.
	pi = symp_h_ratio * gamma_y / (eta + (gamma_y - eta   ) * symp_h_ratio )  # symp_h_ratio is an array of size risk * age
	# omega_e - relative infectiousness in E, IY, IA // symp_h_ratio_overall length age. 
  #omega_e = ((symp_h_ratio_overall / eta) + ((1 - symp_h_ratio_overall ) / gamma_y)) * 
	#					omega_y * sigma * PROP_TRANS_IN_E / (1 - PROP_TRANS_IN_E)            
	omega_e = ((symp_h_ratio / eta) + ((1 - symp_h_ratio ) / gamma_y)) * 
						omega_y * sigma * PROP_TRANS_IN_E / (1 - PROP_TRANS_IN_E)            
	# length age
	omega_a = ((symp_h_ratio_overall / eta) + ((1 - symp_h_ratio_overall) / gamma_y_c)) * 
						omega_y * sigma_c * PROP_TRANS_IN_E / (1 - PROP_TRANS_IN_E) ;
	
	

S=1; E=2; IY=3; IA=4; IH=5; RAY=6; RH=7 ; D=8
ZERO = array(0, c(5,N.pat,2,8))
n=length(ZERO)

oo=array(1:length(ZERO),dim(ZERO))
# each entry in o1, o2 says where it comes from, from which entry in dX1, dX2 we should add.
o1=ZERO;o2=ZERO;o1[]=oo[,,,D];o2[]=oo[,,,D] # initially, everything comes from D, because D will not change, so dX1, dX2 for D is 0.
oo[,,,c(S)] ->o1[,,,c(E)]
oo[,,,c(E)] ->o1[,,,c(IA)]; oo[,,,c(E)] ->o2[,,,c(IY)]
oo[,,,c(IY)]->o1[,,,c(IH)]; oo[,,,c(IY)]->o2[,,,c(RAY)]
oo[,,,c(IH)]->o1[,,,c(D)];  oo[,,,c(IH)]->o2[,,,c(RH)]
oo[,,,c(IA)]->o1[,,,c(RAY)]


# o1[,,c(S,IY,RH)] are themselves, and dI1 needs to be 0 there.
# o2[,,c(S,IA,IH,D,RH)] are themselves, and dI2 needs to be 0 there.


#c1 - How much does each category contribute to infections

c1 = ZERO # 0
c1[,,,E]  = omega_e
c1[,,,IY] = omega_y
c1[,,,IH] = omega_h
c1[,,,IA] = omega_a

c2 = ZERO
c2[,,,S] = 1

c3 = ZERO
c3[,,,E]  = sigma
c3[,,,IA] = gamma_a
c3[,,,IY] = (1-pi)*gamma_y + pi*eta
c3[,,,IH] = (1-nu)*gamma_h + nu*mu

p2 = ZERO
p2[,,,E] = tau
p2[,,,IY] = (1-pi)*gamma_y / ( (1-pi)*gamma_y + pi*eta )
p2[,,,IH] = (1-nu)*gamma_h / ((1-nu)*gamma_h + nu*mu)


SEIR.sto=function(X,beta,dt=1) {
  II=c(apply( c(apply(X*c1,c(1,2),sum)) * (phi.L * beta *dt) ,c(3,2),sum))
#  II=c(rowSums(X*c1) %*% phi)   # how many infect each age of S
  p1=II*c2+c3                    # calculate transition rates
  dX = rbinom( n,  X, 1-exp(-p1*dt))               # how many move to new state
  dX1= rbinom( n, dX, exp(-p2*dt))             # select between two possible next states for some
  dX2= dX-dX1                    # other possibile state
  X1=X-dX+dX1[o1]+dX2[o2]        # o1 and o2 say what adds to what state
  X1
}

SEIR.det=function(X,beta,dt=1) {
  II=c(apply( c(apply(X*c1,c(1,2),sum)) * phi.L * beta *dt ,c(3,2),sum))
  
#  II=c(rowSums(X*c1) %*% phi)   # how many infect each age of S
  p1=II*c2*beta+c3                    # calculate transition rates
  dX=   X*(1-exp(-p1*dt))               # how many move to new state
  dX1= dX*(exp(-p2*dt))             # select between two possible next states for some
  dX2=dX-dX1                    # other possibile state
  X1=X-dX+dX1[o1]+dX2[o2]        # o1 and o2 say what adds to what state
  X1
}
  list( det=SEIR.det, sto=SEIR.sto )
}

SEIR=make.SEIR.f(N.pat=3)
SEIR.det = SEIR$det
SEIR.sto = SEIR$sto


```



Now we can use it.
We need to speci


```{r}
# How many long term facilities are there, how big
N.LTC=54; LTC.size=2
# How many workers visit each facility every day
worker.n=0
# beta for Metro before and after
beta1 = 0.035; beta2 = beta1 *(1-0.80)
# beta for LTC
betaLTC = 0.1
# how long in beta1
T1 = 17


N.pat=N.LTC+1; pat.size=LTC.size



# make functions for model
SEIR=make.SEIR.f(N.pat=N.pat, pat.size=200)
SEIR.det = SEIR$det
SEIR.sto = SEIR$sto

# Just for convenience
S=1; E=2; IY=3; IA=4; IH=5; RAY=6; RH=7 ; D=8


X = array(0,c(5,N.pat,2,8),dimnames=list(colnames(a),c("M",rep("LTC",N.pat-1)),1:2,
                                         c("S","E","IY","IA","IH","RAY","RH","D")))
X[,1,,S] = t(Pop_Metro2)
X[ , 1, ,E] = 10
# calc how many in each facility are in each risk group
p.risk = Pop_Metro2[,5]/sum(Pop_Metro2[,5])
# put them in
X[5,-1,,S] = rep(round(p.risk * LTC.size), each=N.LTC)
# subtract from Metro pop
X[5,1,,S] = X[5,1,,S] - apply(X[5,-1,,S,drop=F],3,sum)

Xt=array(0,c(200,N.pat,8))
dimnames(Xt)[[3]]=dimnames(X)[[4]]

Nar=length(X[3,1,,]); # age x risk = 10
Npop=sum(X[3,1,,])    # num of adults

# Beta needs to be a big structure so it just multiplies all compartments
# 1st and 3rd dim are simply age, so can be ignored, 2nd dim is patch, so Metro=1
# LTC = 2..N.pat
bt=array(0,c(5,N.pat,5))
bt1=bt; bt1[,1,]=beta1 ; bt1[,-1,]= betaLTC
bt2=bt; bt2[,1,]=beta2 ; bt2[,-1,]= betaLTC
for( i in 1:T1) { 
  # sample workers from adults
  workers=array( rbinom(Nar*(N.pat-1), rep(X[3,1,,],N.pat-1), prob= worker.n/ Npop ), c(2,8,N.pat-1))
  # remove from Metro
  X[3, 1,,]=X[3,1,,]-apply(workers,c(1,2),sum)
  # add to LTC
  X[3,-1,,]=X[3,-1,,]+aperm(workers,c(3,1,2))
  # half day forward
  X=SEIR.sto(X,beta=bt1,dt=0.5)
  Xt[i,,] = apply(X,c(2,4),sum)
#  Xt[i,,] = apply(X,c(2,4),sum)
  # Add workers for the night
  X[3,1,,] = X[3,1,,]+ apply(X[3,-1,,,drop=F],c(3,4),sum)
  # remove from LTC
  X[3,-1,,] = 0
  # another half day
  X=SEIR.sto(X,beta=bt1,dt=0.5)
}
for( i in (T1+1):200) { 
  workers=array( rbinom(Nar*(N.pat-1), rep(X[3,1,,],N.pat-1), prob= worker.n/ Npop ), c(2,8,N.pat-1))
  X[3, 1,,]=X[3,1,,]-apply(workers,c(1,2),sum)
  X[3,-1,,]=X[3,-1,,]+aperm(workers,c(3,1,2))
  X=SEIR.sto(X,beta=bt2,dt=0.5)
  Xt[i,,] = apply(X,c(2,4),sum)
#  Xt[i,,] = apply(X,c(2,4),sum)
  X[3,1,,] = X[3,1,,]+ apply(X[3,-1,,,drop=F],c(3,4),sum)
  X[3,-1,,] = 0
  X=SEIR.sto(X,beta=bt2,dt=0.5)
}
plot( (1:200)/2, apply( Xt[,  ,IH],1,sum),type="l", ylab="heads in beds",xlab="days")
lines((1:200)/2,apply( Xt[,-1,IH],1,sum),col=2)
plot( (1:200)/2,apply( Xt[,  ,IY],1,sum),type="l", ylab="symptomatic cases",xlab="days")
lines( (1:200)/2,apply( Xt[,-1,IY],1,sum),col=2)
plot( (1:200)/2,apply( Xt[,  ,RAY],1,sum),type="l")
lines((1:200)/2, apply( Xt[,-1,RAY],1,sum),col=2)
plot((1:200)/2,Xt[,1,D])
plot((1:200)/2,Xt[,2,D])
plot((1:200)/2,Xt[,2,IY],ylim=c(0,60),type="l")
for( i in 3:55) {
  lines( (1:200)/2,Xt[,i,IY],col=rainbow(54)[i])
}

plot((1:200)/2,apply(Xt[,-1,D],1,sum)/apply(Xt[,,D],1,sum),main="Fraction of deaths from LTC", ylab="fraction",xlab="days",ylim=0:1,type="l")
plot((1:200)/2,apply(Xt[,-1,IH],1,sum)/apply(Xt[,,IH],1,sum),main="Fraction in Hospital from LTC", ylab="fraction",xlab="days",ylim=0:1,type="l")

```

```{r}
# How many long term facilities are there, how big
N.LTC=54; LTC.size=2
# How many workers visit each facility every day
worker.n=0
# beta for Metro before and after
beta1 = 0.035; beta2 = beta1 *(1-0.93)
# beta for LTC
betaLTC = 0.1
# how long in beta1
T1 = 26


N.pat=N.LTC+1; pat.size=LTC.size



# make functions for model
SEIR=make.SEIR.f(N.pat=N.pat, pat.size=200)
SEIR.det = SEIR$det
SEIR.sto = SEIR$sto

# Just for convenience
S=1; E=2; IY=3; IA=4; IH=5; RAY=6; RH=7 ; D=8


X = array(0,c(5,N.pat,2,8),dimnames=list(colnames(a),c("M",rep("LTC",N.pat-1)),1:2,
                                         c("S","E","IY","IA","IH","RAY","RH","D")))
X[,1,,S] = t(Pop_Metro2)
X[ , 1, ,E] = 10
# calc how many in each facility are in each risk group
p.risk = Pop_Metro2[,5]/sum(Pop_Metro2[,5])
# put them in
X[5,-1,,S] = rep(round(p.risk * LTC.size), each=N.LTC)
# subtract from Metro pop
X[5,1,,S] = X[5,1,,S] - apply(X[5,-1,,S,drop=F],3,sum)

Xt=array(0,c(200,N.pat,5,8),dimnames=list())
dimnames(Xt)[[4]]=dimnames(X)[[4]]

Nar=length(X[3,1,,]); # age x risk = 10
Npop=sum(X[3,1,,])    # num of adults

# Beta needs to be a big structure so it just multiplies all compartments
# 1st and 3rd dim are simply age, so can be ignored, 2nd dim is patch, so Metro=1
# LTC = 2..N.pat
bt=array(0,c(5,N.pat,5))
bt1=bt; bt1[,1,]=beta1 ; bt1[,-1,]= betaLTC
bt2=bt; bt2[,1,]=beta2 ; bt2[,-1,]= betaLTC
for( i in 1:T1) { 
  # sample workers from adults
  workers=array( rbinom(Nar*(N.pat-1), rep(X[3,1,,],N.pat-1), prob= worker.n/ Npop ), c(2,8,N.pat-1))
  # remove from Metro
  X[3, 1,,]=X[3,1,,]-apply(workers,c(1,2),sum)
  # add to LTC
  X[3,-1,,]=X[3,-1,,]+aperm(workers,c(3,1,2))
  # half day forward
  X=SEIR.sto(X,beta=bt1,dt=0.5)
  Xt[i,,,] = apply(X,c(2,1,4),sum)
#  Xt[i,,] = apply(X,c(2,4),sum)
  # Add workers for the night
  X[3,1,,] = X[3,1,,]+ apply(X[3,-1,,,drop=F],c(3,4),sum)
  # remove from LTC
  X[3,-1,,] = 0
  # another half day
  X=SEIR.sto(X,beta=bt1,dt=0.5)
}
for( i in (T1+1):200) { 
  workers=array( rbinom(Nar*(N.pat-1), rep(X[3,1,,],N.pat-1), prob= worker.n/ Npop ), c(2,8,N.pat-1))
  X[3, 1,,]=X[3,1,,]-apply(workers,c(1,2),sum)
  X[3,-1,,]=X[3,-1,,]+aperm(workers,c(3,1,2))
  X=SEIR.sto(X,beta=bt2,dt=0.5)
  Xt[i,,,] = apply(X,c(2,1,4),sum)
#  Xt[i,,] = apply(X,c(2,4),sum)
  X[3,1,,] = X[3,1,,]+ apply(X[3,-1,,,drop=F],c(3,4),sum)
  X[3,-1,,] = 0
  X=SEIR.sto(X,beta=bt2,dt=0.5)
}
```



```{r}
plot( cumsum(apply(Xt[,1,,IH],1,sum)))
plot(cumsum(Xt[,1,5,IH])/ cumsum(apply(Xt[,1,,IH],1,sum)))
plot(Xt[,1,5,IH])
```


```
plot( apply(Xt[,1,,IH],1,sum)){r}

```




```{r}
plot((1:200)/2,apply( Xt2[,,D],1,sum),type="n", ylab="deaths",xlab="days")
lines( (1:200)/2, apply( Xt[,  ,D],1,sum))
lines((1:200)/2,apply( Xt[,-1,D],1,sum),col=2)
lines((1:200)/2,apply( Xt2[,,D],1,sum),col=3)

```



Try without LTC

```{r}
# How many long term facilities are there, how big
N.LTC=2; LTC.size=20
# How many workers visit each facility every day
worker.n=2
# beta for Metro before and after
beta1 = 0.3; beta2 = 0.1
# beta for LTC
betaLTC = 2
# how long in beta1
T1 = 30 


N.pat=N.LTC+1; pat.size=LTC.size



# make functions for model
SEIR=make.SEIR.f(N.pat=N.pat, pat.size=200)
SEIR.det = SEIR$det
SEIR.sto = SEIR$sto

# Just for convenience
S=1; E=2; IY=3; IA=4; IH=5; RAY=6; RH=7 ; D=8


X = array(0,c(5,N.pat,2,8),dimnames=list(colnames(a),c("M",rep("LTC",N.pat-1)),1:2,
                                         c("S","E","IY","IA","IH","RAY","RH","D")))
X[,1,,S] = t(Pop_Metro2)
X[ , 1, ,E] = 10
# calc how many in each facility are in each risk group
p.risk = Pop_Metro2[,5]/sum(Pop_Metro2[,5])
# put them in
X[5,-1,,S] = rep(round(p.risk * LTC.size), each=N.LTC)
# subtract from Metro pop
X[5,1,,S] = X[5,1,,S] - apply(X[5,-1,,S,drop=F],3,sum)

Xt=array(0,c(200,N.pat,8))
dimnames(Xt)[[3]]=dimnames(X)[[4]]

Nar=length(X[3,1,,]); # states x risk = 16
Npop=sum(X[3,1,,])    # num of adults

# Beta needs to be a big structure so it just multiplies all compartments
# 1st and 3rd dim are simply age, so can be ignored, 2nd dim is patch, so Metro=1
# LTC = 2..N.pat
bt=array(0,c(5,N.pat,5))
bt1=bt; bt1[,1,]=beta1 ; bt1[,-1,]= betaLTC
bt2=bt; bt2[,1,]=beta2 ; bt2[,-1,]= betaLTC
for( i in 1:T1) { 
  # sample workers from adults
  workers=array( rbinom(Nar*(N.pat-1), rep(X[3,1,,],N.pat-1), prob= worker.n/ Npop ), c(2,8,N.pat-1))
  # remove from Metro
  X[3, 1,,]=X[3,1,,]-apply(workers,c(1,2),sum)
  # add to LTC
  X[3,-1,,]=X[3,-1,,]+aperm(workers,c(3,1,2))
  # half day forward
  X=SEIR.sto(X,beta=bt1,dt=0.5)
  Xt[i,,] = apply(X,c(2,4),sum)
#  Xt[i,,] = apply(X,c(2,4),sum)
  # Add workers for the night
  X[3,1,,] = X[3,1,,]+ apply(X[3,-1,,,drop=F],c(3,4),sum)
  # remove from LTC
  X[3,-1,,] = 0
  # another half day
  X=SEIR.sto(X,beta=bt1,dt=0.5)
}
for( i in (T1+1):200) { 
  workers=array( rbinom(Nar*(N.pat-1), rep(X[3,1,,],N.pat-1), prob= worker.n/ Npop ), c(2,8,N.pat-1))
  X[3, 1,,]=X[3,1,,]-apply(workers,c(1,2),sum)
  X[3,-1,,]=X[3,-1,,]+aperm(workers,c(3,1,2))
  X=SEIR.sto(X,beta=bt2,dt=0.5)
  Xt[i,,] = apply(X,c(2,4),sum)
#  Xt[i,,] = apply(X,c(2,4),sum)
  X[3,1,,] = X[3,1,,]+ apply(X[3,-1,,,drop=F],c(3,4),sum)
  X[3,-1,,] = 0
  X=SEIR.sto(X,beta=bt2,dt=0.5)
}
plot(Xt[,1,IH])
plot(Xt[,1,D])
plot(Xt[,2,D])

plot(apply(Xt[,-1,D],1,sum)/apply(Xt[,,D],1,sum),main="Fraction of deaths from LTC")
plot(apply(Xt[,-1,D],1,sum)/apply(Xt[,,D],1,sum),main="Fraction in H from LTC")

```
